import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Note } from "../state/types";

/**
 * Notes are exported to `.parley/notes.md`, versioned in git: they cross
 * machines, reach a colleague, and outlive the project. This is the part of the
 * old markdown board that was worth keeping.
 *
 * No automatic commit. A human or an agent commits it, on purpose.
 */
export function exportNotes(notes: Note[], repoRoot: string): string {
  const dir = join(repoRoot, ".parley");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "notes.md");

  const body = notes.length
    ? notes
        .map((n) => {
          const tags = n.tags.length ? `\n\n**Tags:** ${n.tags.map((t) => `\`${t}\``).join(", ")}` : "";
          return `## ${n.title}\n\n_${n.authorName} · ${n.at}_${tags}\n\n${n.body}`.trimEnd();
        })
        .join("\n\n---\n\n")
    : "_No notes yet._";

  writeFileSync(
    path,
    `# parley notes\n\nDurable knowledge for every front working in this repository, present and\nfuture. Generated by \`parley notes --export\`; edit through parley, not by hand.\n\n---\n\n${body}\n`,
    "utf8",
  );
  return path;
}
